### ISSUE TITLE
ALlow to convert salt during mercator

### ISSUE THREAD

**Issue by yav** [yav/concordia#14]

**Comment by dmk11** [comment]
Shouldn’t you allow to convert during architect, tribune and senator too?

**Comment by yav** [comment]
In theory salt should be usable for payments already (although I haven't tested it).  I need to do something if you want to sell it though

**Comment by yav** [comment]
I wonder if it makes sense to just automatically always sell it as cloth, as you'd get the most money

**Comment by dmk11** [comment]
No it doesn’t because is the 2 type limit.
