### ISSUE TITLE
Update logs with city and region names

### ISSUE THREAD

**Issue by dmk11** [yav/concordia#16]
Log file says “this” city or this region instead of actual names

**Comment by yav** [comment]
When you hover over them it highlights the city/region/path in question.  Perhaps I should make it clickable though, so that one can use it from a tablet or phone.   We could add names but then we'd have to type them all in...

**Comment by dmk11** [comment]
I guess I wasn’t able to see it since I was on my phone. I guess you can leave it as is. Not many would play on phone
