### ISSUE TITLE
Sea colonist allowed to be build inland 

### ISSUE THREAD

**Issue by dmk11** [yav/concordia#19]
I played colonist card and placed a boat inland and was allowed to :)

**Comment by yav** [comment]
I was wondering if you are allowed to do that.  I though you might want to do it, if you are just trying to get more workers  out on the board but you only have houses in land cities, and only ships left in stock.   Do you think I should disable it?  Not sure if the captial always has access to both, in which case you could always put things there instead...

**Comment by dmk11** [comment]
You should disable it. There’s no reason why you should be able to do this. Just keep making more on capital since there’s no limit on how many hours can have in a city
