### ISSUE TITLE
Show who has Prefectus Magnus

### ISSUE THREAD

**Issue by yav** [yav/concordia#2]

**Comment by dmk11** [comment]
I don’t see PM indicator. A “PM” icon next to player name would be clearer. 
also, log file doesn’t say when PM is passed. Would be nice to indicate that and say who it passed to.

**Comment by yav** [comment]
The little eagle next to a player is supposed to indicate the PM, can you see it or has it disappeared for some reason?  Looks like this:
![image](https://github.com/user-attachments/assets/4a8e2d93-9bee-46d8-816d-c8bffed398fa)

Good idea on updating the log file btw.

**Comment by dmk11** [comment]
Ok. I didn’t notice it but I guess there was an eagle. Didn’t realized it means PM. 
also, for people who doesn’t have it memorized like me, it would be nice to have the resource cost when doing Mercator.
