### ISSUE TITLE
Undo during Mercator 

### ISSUE THREAD

**Issue by dmk11** [yav/concordia#25]
After buying stuff if you undo, seems like the prompt for buying things was redrawn without clearing previous prompts.

**Comment by dmk11** [comment]
![IMG_1375](https://github.com/user-attachments/assets/42eb1428-01f4-4a3e-8185-0ba17a9099d8)

**Comment by yav** [comment]
Hm, it is likely something is crashing in the UI (should disappear if you reload?).  I can't seem to make it do this though... Did you do you it by playing Mercator first or some other sequence of actions?

**Comment by dmk11** [comment]
Yes, it fixes itself after reload. 
I believe I tried to do prefect first, then undo (a few times) and then I tried Mercator (undo and redo, multiple times). 
another variable is that I was coming from a very slow internet connection. And had to refresh a few times.

**Comment by yav** [comment]
I made some changes that might fix this, but I am not quite sure why it's happening.  I think I'll close it for now, and let's reopen if we can figure out how to reproduce reliably
