### ISSUE TITLE
Display issue with offset bonus marker

### ISSUE THREAD

**Issue by dmk11** [yav/concordia#37]
Only happens in certain browser/setting?
Try Chrome

 Also some icons (mostly the colonists, houses seems to work ok) don't get moved when resizing window

**Comment by yav** [comment]
So the issue here because of the scrollbars: if you have them big things are offset, so I have to account for the widths of the scrollbars when computing the positions of things

**Comment by dmk11** [comment]
seems like a minor issue you should put at low priority.  Since refresh fixes it.
